### ISSUE TITLE
Error while creating a model

### ISSUE THREAD

**Issue by cobraprojects** [phpsquad/domain-maker#2]
I try to create a model using the next command:

`php artisan domain:make:model -m Book Author`

and I got this error

`File does not exist at path my-laravel-path/vendor/phpsquad/domain-maker/src/Console/stubs/model.stub`

I also wish you add  `Database/migratations` and `resources/views` folders inside the domain folder as well

thanks in advance

**Comment by rohrig** [comment]
@cobraprojects Set default stub path for model. Should be working now. Let me know if it's still giving you trouble after updating.

**Comment by rohrig** [comment]
fixed
