### ISSUE TITLE
foreach() argument must be of type array|object, null given

### ISSUE THREAD

**Issue by djoudi** [phpsquad/domain-maker#4]
`
> @php artisan package:discover --ansi

   ErrorException

  foreach() argument must be of type array|object, null given

  at C:\Users\info\apps\demande\vendor\phpsquad\domain-maker\src\ViewProvider.php:28
     24▕     $this->app->bind('view.finder', function ($app) use ($domainMakerViews) {
     25▕
     26▕       $paths = $app['config']['view.paths'];
     27▕
  ➜  28▕       foreach ($domainMakerViews as $path) {
     29▕         $paths[] = $path;
     30▕       }
     31▕
     32▕       return new FileViewFinder($app['files'], $paths);

  1   C:\Users\info\apps\demande\vendor\phpsquad\domain-maker\src\ViewProvider.php:28
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("foreach() argument must be of type array|object, null given", "C:\Users\info\apps\demande\vendor\phpsquad\domain-maker\src\ViewProvider.php")

  2   C:\Users\info\apps\demande\vendor\laravel\framework\src\Illuminate\Container\Container.php:873
      PhpSquad\DomainMaker\ViewProvider::PhpSquad\DomainMaker\{closure}(Object(Illuminate\Foundation\Application), [])
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
`

**Comment by rohrig** [comment]
@djoudi When are you getting this error?

**Comment by hakimzulkufli** [comment]
I had this issue after installing this package. It happens after trying to access the project on the browser without creating the `app/Domains` folder first.

**Comment by rohrig** [comment]
I believe commit:  39e864c14e50999114b814ccfe13dbc78dc3e176 fixes this. @hakimzulkufli  please confirm if you have time.
