### ISSUE TITLE
Composer autoload PSR-4 issue 

### ISSUE THREAD

**Issue by sabbir-rupom** [phpsquad/domain-maker#5]
Getting this message while composer update in laravel 

`Class PhpSquad\DomainMaker\Console\MigrateCommand located in C:/wamp64/www/laravel-app/vendor/phpsquad/domain-maker/src\Console\DomainMigrateCommand.php does not comply with psr-4 autoloading standard. Skipping.`

**Comment by rohrig** [comment]
HI, thanks for the heads up. The problem was that class name was incorrect. I  renamed the class and it should be working correctly now. Just run `composer update  "phpsquad/domain-maker"` and that should do it.
