### ISSUE TITLE
Cannot run artisan commands if there's a file in Domains directory

### ISSUE THREAD

**Issue by hakimzulkufli** [phpsquad/domain-maker#6]
The package breaks when trying to run the artisan commands if there is a file in the Domains directory.

Errors:
```
scandir(/mnt/www/my-laravel-app/app/Domains/.gitkeep): Failed to open directory: Not a directory

at vendor/phpsquad/domain-maker/src/ViewProvider.php:44
     40▕ 
     41▕         $domains = array_diff(scandir(base_path('app/Domains')), array('.', '..'));
     42▕ 
     43▕         foreach ($domains as $domain) {
 ➜  44▕             $dirs = array_diff(scandir(base_path('app/Domains/' . $domain)), array('.', '..'));
     45▕             $resourcesDirExists = in_array('resources', $dirs);
     46▕             if (!$resourcesDirExists) {
     47▕                 continue;
     48▕             }
```

Same instances of this error are also found in `vendor/phpsquad/domain-maker/src/DomainRouteServiceProvider.php:26`.

I have a `README.md` file in the `app/Domains` to let my team know why the `Domains` folder exist and how to add more Domains.
I also have `.gitkeep` files in the empty directories so that I can push the empty directories into my repository.

Maybe the package can check if `$domain` in the loop is a directory using `is_dir()`?
Another suggestion is to use a different way to grab directories only using `glob()` instead of `scandir()`.

**Comment by rohrig** [comment]
6b62f9812f71d22daf0028a004cff2f26cd44de3 fixes this issue
